site_name: Alicia Foxx
site_author: Alicia Foxx

nav:
  - Home: index.md
  - People: people.md
  - Fundamental Ecology: berc.md
  - Applied Ecology: ecology.md
  - Improving the Scientific Interprise: synthesis.md
  - Resources: resources.md

markdown_extensions:
  - attr_list
  
# Configuration
theme:
  name: material
  palette:
    primary: purple
    accent: cyan
  font:
    text: Ubuntu
  icon:
    logo: material/cloud
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top

  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime    
  # logo: PyTorch_logo_icon.svg
  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/c17hawke
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/c17hawke
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/c17hawke
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/c17hawke/

copyright: |
  &copy; 2022 <a href="https://github.com/aliciafoxx"  target="_blank" rel="noopener">Alicia Foxx</a>
